version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'staging'
    schedule:
      interval: 'daily'
    reviewers:
      - 'longtomjr'
      - 'sabinebertram'
    assignees:
      - 'longtomjr'
    # Disable for now, pending Yarn 2 support.
    # Upstream issue: https://github.com/dependabot/dependabot-core/issues/1297
    open-pull-requests-limit: 0

  - package-ecosystem: 'docker'
    directory: '/'
    target-branch: 'staging'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'longtomjr'
      - 'sabinebertram'
    assignees:
      - 'longtomjr'
