version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'staging'
    schedule:
      interval: 'daily'
    reviewers:
      - 'longtomjr'
      - 'sabinebertram'
    assignees:
      - 'longtomjr'

  - package-ecosystem: 'docker'
    directory: '/'
    target-branch: 'staging'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'longtomjr'
      - 'sabinebertram'
    assignees:
      - 'longtomjr'
