packageExtensions:
  # Missing peer dependencies:
  '@nestjs/graphql@*':
    peerDependencies:
      # For @nestjs/mapped-types
      class-transformer: ^0.3.2
      class-validator: ^0.13.1
  nestjs-graphql-dataloader@*:
    peerDependencies:
      # For @nestjs/graphql
      class-transformer: ^0.3.2
      class-validator: ^0.13.1
      graphql: ^15.0.0
      # For @nestjs/common, @nestjs/core, @nestjs/graphql
      reflect-metadata: ^0.1.12

  # https://github.com/apollographql/apollo-server/issues/4451
  apollo-engine-reporting-protobuf@*:
    dependencies:
      '@types/long': ^4.0.0
  apollo-reporting-protobuf@*:
    dependencies:
      '@types/long': ^4.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.0.2.cjs
