packageExtensions:
  '@nestjs/graphql@*':
    dependencies:
      graphql-tools: '*'
  apollo-engine-reporting-protobuf@*:
    dependencies:
      '@types/long': ^4.0.0
  apollo-reporting-protobuf@*:
    dependencies:
      '@types/long': ^4.0.0
  nestjs-pino@*:
    dependencies:
      '@types/pino': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-2.4.0.cjs
