yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "nestjs-pino@*":
    dependencies:
      "@types/pino": "*"
  "apollo-engine-reporting-protobuf@*":
    dependencies:
      "@types/long": "^4.0.0"
  "apollo-reporting-protobuf@*":
    dependencies:
      "@types/long": "^4.0.0"
  "@nestjs/graphql@*":
    dependencies:
      graphql-tools: "*"
      apollo-env: "*"

