packageExtensions:
  # Missing peer dependencies:
  '@nestjs/graphql@*':
    dependencies:
      graphql-tools: '*'
    peerDependencies:
      # For @nestjs/mapped-types
      class-transformer: ^0.3.2
      class-validator: ^0.13.1

  # https://github.com/apollographql/apollo-server/issues/4451
  apollo-engine-reporting-protobuf@*:
    dependencies:
      '@types/long': ^4.0.0
  apollo-reporting-protobuf@*:
    dependencies:
      '@types/long': ^4.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.0.2.cjs
