version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.2.1
  kube-orb: circleci/kubernetes@0.11.0

jobs:
  build: 
    executor: 
      name: node/default
      tag: current
    steps: 
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - package.json
            - dist
            
workflows:
    build-and-push:
      jobs:
        - node/test:
            pkg-manager: yarn
            version: 14.4.0
            run-command: "test -w 1"
        - build
        - docker/publish:
            filters:
              branches:
                only:
                  - staging
                  - master
            executor:
                name: docker/machine
                # dlc: true
            requires:
              - build
            after_checkout:
              - attach_workspace:
                  at: .
            image: registree-core
            registry: $DOCKER_REGISTRY
            docker-password: DOCKER_LOGIN
            docker-username: DOCKER_PASSWORD
            tag: $CIRCLE_SHA1
