version: 2.1
orbs:
  node: circleci/node@4.1.0
  docker: circleci/docker@1.2.1
  kube-orb: circleci/kubernetes@0.11.0
  codecov: codecov/codecov@1.1.2

jobs:
  test:
    executor:
      name: node/default
      tag: current
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: yarn install --immutable
          pkg-manager: yarn
      - run:
          command: yarn test:cov -w 1
      - codecov/upload:
          file: 'coverage/lcov.info'
  build:
    executor:
      name: node/default
      tag: current
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: yarn install --immutable
          pkg-manager: yarn
      - run:
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - '.yarn'
            - package.json
            - dist
            - '.pnp.js'
            - yarn.lock

workflows:
  build-and-push:
    jobs:
      - test
      - build
      - docker/publish:
          filters:
            branches:
              only:
                - staging
                - master
          executor:
            name: docker/machine
            # dlc: true
          requires:
            - build
          after_checkout:
            - attach_workspace:
                at: .
          image: registree-core
          registry: $DOCKER_REGISTRY
          docker-password: DOCKER_LOGIN
          docker-username: DOCKER_PASSWORD
          tag: $CIRCLE_SHA1
